### ISSUE TITLE
Webpack throws an 'Unexpected Token' error when parsing IPut

### ISSUE THREAD

**Issue by SilentStormm** [lizheming/iput#3]
I'm trying to use IPut in my Electron + React app but it throws the following error on compilation:
```
[0] Failed to compile.
[0]
[0] ./node_modules/iput/src/index.jsx 10:22
[0] Module parse failed: Unexpected token (10:22)
[0] You may need an appropriate loader to handle this file type, currently no loaders ar
e configured to process this file. See https://webpack.js.org/concepts#loaders
[0] |    * set default props
[0] |    */
[0] >   static defaultProps = {
[0] |     className: '',
[0] |     defaultValue: '...',
```

**Comment by lizheming** [comment]
Hello, you should add https://babeljs.io/docs/en/babel-plugin-proposal-class-properties this plugin to your babel config.

**Comment by ifisidro** [comment]
> Hello, you should add https://babeljs.io/docs/en/babel-plugin-proposal-class-properties this plugin to your babel config.

As a suggestion: You should, in fact, publish it already built into a /dist folder and then reference its entrypoint in your 'index.js'. That would be the appropriate approach.

**Comment by lizheming** [comment]
@ifisidro Yes, you are right. I have update build config with your suggestion. Now you can import it with compiled file, please upgrade to `1.1.0` version. Thank you very much!
