### ISSUE TITLE
[feature request] type dot then jump to next part

### ISSUE THREAD

**Issue by oe** [lizheming/iput#4]
As mentioned in title, it will be convenient and efficient.

**Comment by lizheming** [comment]
That's pretty a good idea, `iput@1.1.1` have support it and released few minutes ago, thank you for your advice!

**Comment by oe** [comment]
but seems not working in https://lizheming.github.io/iput/

**Comment by lizheming** [comment]
OK, it works now! @oe

**Comment by oe** [comment]
great!

**Comment by oe** [comment]
Another issue:  
type dot before any number at the last input, error occurred.  e.g.:

1. `.1`  => 255
2. `1.1` => 1

**Comment by lizheming** [comment]
@oe It's a javascript `parseInt` problem. try `parseInt('.1')` and `parseInt('1.1')`, I thought you can understand it.

**Comment by oe** [comment]
Just review the code, this is not the root cause.

Change the following code 

https://github.com/lizheming/iput/blob/5b87430923f80685ba6869171ba8ce2f974b2a4a/src/index.js#L70-L73

to

```js
if (e.keyCode === 190) { 
   e.preventDefault(); 
   if (i < 3) { domId = i + 1; }
 } 
```

can fix this issue

**Comment by lizheming** [comment]
OK, I think I have understood what you meaning, let us fix it.

**Comment by oe** [comment]
Further info: React use native `input` event to deal with `onChange` props, and `input` triggered after `keydown`.

So, your code should work fine, but need change a little.

**Comment by lizheming** [comment]
Yes, `onKeydown` should always be triggered before `onChange`. I misunderstand what you said and think you're past string into input. I have fix it as you mentioned and release `iput@1.1.2`, please enjoy it.

**Comment by oe** [comment]
My bad.

Now everything works fine, great job!

**Comment by lizheming** [comment]
OK, thank you for your idea, solution code and test. 😄

**Comment by oe** [comment]
🤝
